name: Build and Publish Installer

on:
  push:
    tags:
      - 'v*'
    workflow_dispatch:
    
permissions:
  contents: write
  packages: write
  issues: write

jobs:
  ci_build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get Version Number
      id: get-version-number
      run: |
        TAG=$${{  github.ref_name }}
        echo Version: ${TAG#v}
        echo "VERSION=${TAG#v}" >> "$GITHUB_OUTPUT"
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --verbose --release
    - name: Set path for candle and light
      run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH
      shell: bash
    - name: Install cargo-wix
      run: cargo install cargo-wix
    - name: Build Installer
      run: cargo wix --nocapture
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          target/wix/cua-${{ steps.get-version-number.outputs.VERSION }}-x86_64.msi